spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle11gDialect
      javax:
        persistence:
          query:
            timeout: 600000
    open-in-view: true
  datasource:
    url: jdbc:oracle:thin:@cdb.cmis.az:1521:GDBCSCP1
    username: root
    password: ayaz1997
    driver-class-name: oracle.jdbc.OracleDriver




server:
  port: 8080
  servlet:
    context-path: /api/mdm
  address: 192.168.250.89